# Generated by Django 5.2 on 2025-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_parent_task',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
